FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*

ARG TEMPLATE_FOLDER=templates_example
ENV TEMPLATE_FOLDER=${TEMPLATE_FOLDER}

ARG STATIC_JINJA_VERSION=main  
# Загрузка при помощи ADD
ADD https://github.com/MrDave/StaticJinjaPlus/archive/refs/heads/${STATIC_JINJA_VERSION}.zip /opt/StaticJinjaPlus.zip
WORKDIR /opt
RUN unzip StaticJinjaPlus.zip && \
    mv StaticJinjaPlus-${STATIC_JINJA_VERSION} StaticJinjaPlus && \
    rm StaticJinjaPlus.zip

WORKDIR /opt/StaticJinjaPlus
RUN pip install --no-cache-dir -r requirements.txt

CMD ["sh", "-c", "python main.py --srcpath $TEMPLATE_FOLDER"]
