FROM ubuntu:24.10

RUN apt-get update && apt-get install -y  python3 python3-pip  python3-full  git  && rm -rf /var/lib/apt/lists/* 

ARG TEMPLATE_FOLDER=templates_example
ENV TEMPLATE_FOLDER=${TEMPLATE_FOLDER}

ARG STATIC_JINJA_VERSION=main

RUN git clone --branch ${STATIC_JINJA_VERSION} https://github.com/MrDave/StaticJinjaPlus.git /opt/StaticJinjaPlus

WORKDIR /opt/StaticJinjaPlus

RUN pip install -r requirements.txt --break-system-packages

CMD ["sh", "-c", "python3 main.py --srcpath $TEMPLATE_FOLDER"]
