FROM ubuntu:24.10

RUN apt-get update && apt-get install -y  python3 python3-pip  python3-full  git unzip && rm -rf /var/lib/apt/lists/* 

ARG TEMPLATE_FOLDER=templates_example
ENV TEMPLATE_FOLDER=${TEMPLATE_FOLDER}

ARG STATIC_JINJA_VERSION=main

ADD https://github.com/MrDave/StaticJinjaPlus/archive/refs/heads/${STATIC_JINJA_VERSION}.zip /opt/StaticJinjaPlus.zip

# Установка рабочей директории
WORKDIR /opt

# Установка unzip и распаковка архива
RUN apt-get install -y unzip && \
    unzip StaticJinjaPlus.zip && \
    mv StaticJinjaPlus-${STATIC_JINJA_VERSION} StaticJinjaPlus && \
    rm StaticJinjaPlus.zip

WORKDIR /opt/StaticJinjaPlus

RUN pip install -r requirements.txt --break-system-packages

CMD ["sh", "-c", "python3 main.py --srcpath $TEMPLATE_FOLDER"]
